### ISSUE TITLE
Password Reset Confirm don`t work correctly!

### ISSUE THREAD

**Issue by nurzhannogerbek** [ruddra/django-reset-password#1]
First of all **THANKS** for your project. Unfortunatly I have some problems.

After successful password reset (first step) I have message in my email with next redirect link to next step:
`127.0.0.1:8000/en/account/password-reset-confirm/NA-4ei-53e725f1ba4cbfc54fb8/`

Unfortunately I always have this Message in password_reset_confirm.html template:
`The password reset link was invalid, possibly because it has already been used. Please request a new password reset.`

I also asked this question in StackOverFlow with code details: [http://stackoverflow.com/questions/38960926/password-reset-confirm-dont-work](url)
Please can you check it cause I am really comfused?!

**Comment by ruddra** [comment]
Okay I am looking into it.

**Comment by ruddra** [comment]
Unfortunately the project itself working fine in django 1.9 and I had no problem resetting my password. Though it has few problems with Django 1.10. Still, I am closing this issue, but I will look into your code asap.
